export const data = {
  header_big: [
    'images/westWorldmax.webp',
    'images/Smax.jpg',
    'images/ofmax.jpg',
    'images/hod1920.jpg',
  ],
  slider_img: [
    {
      max: './images/sv1920.webp',
      mm1366: './images/sv1366.webp',
      mm1024: './images/sv1024.webp',
      mm768: './images/sv768.webp',
      min: './images/svmin.webp',
      normal: './images/svdefault.webp',
    },
    {
      max: './images/ss1920.webp',
      mm1366: './images/ss1366.webp',
      mm1024: './images/ss1024.webp',
      mm768: './images/ss768.webp',
      min: './images/ssmin.webp',
      normal: './images/ssdefault.webp',
    },
    {
      max: './images/si1920.webp',
      mm1366: './images/si1366.webp',
      mm1024: './images/si1024.webp',
      mm768: './images/si769.webp',
      min: './images/simin.webp',
      normal: './images/sidefault.webp',
    },
    {
      max: './images/sw1920.webp',
      mm1366: './images/sw1366.webp',
      mm1024: './images/sw1024.webp',
      mm768: './images/sw768.webp',
      min: './images/swmin.webp',
      normal: './images/swdefault.webp',
    },
    {
      max: './images/shalo1920.webp',
      mm1366: './images/shalo1366.webp',
      mm1024: './images/shalo1024.webp',
      mm768: './images/shalo768.webp',
      min: './images/shalomin.webp',
      normal: './images/shalodefault.webp',
    },
    {
      max: './images/sgot1920.webp',
      mm1366: './images/sgot1366.webp',
      mm1024: './images/sgot1024.webp',
      mm768: './images/sgot768.webp',
      min: './images/sgotmin.webp',
      normal: './images/sgotdefault.webp',
    },
    {
      max: './images/scity1920.webp',
      mm1366: './images/scity1366.webp',
      mm1024: './images/scity1024.webp',
      mm768: './images/scity768.webp',
      min: './images/scitymin.webp',
      normal: './images/scitydefault.webp',
    },
  ],
  footer_img: [
    {
      max: './images/brothersmax.webp',
      mm1366: './images/brothers1366.webp',
      mm1024: './images/brothers1024.webp',
      mm768: './images/brothers768.webp',
      min: './images/brothersmin.webp',
      normal: './images/brothersdefault.webp',
    },
    {
      max: './images/firemax.webp',
      mm1366: './images/fire1366.webp',
      mm1024: './images/fire1024.webp',
      mm768: './images/fire768.webp',
      min: './images/firemin.webp',
      normal: './images/firedefault.webp',
    },
    {
      max: './images/bridefathermax.webp',
      mm1366: './images/bridefather1366.webp',
      mm1024: './images/bridefather1024.webp',
      mm768: './images/bridefather768.webp',
      min: './images/bridefathermin.webp',
      normal: './images/bridefatherdefault.webp',
    },
    {
      max: './images/notmemax.webp',
      mm1366: './images/notme1366.webp',
      mm1024: './images/notme1024.webp',
      mm768: './images/notme768.webp',
      min: './images/notmemin.webp',
      normal: './images/notmedefault.webp',
    },
  ],
  FAQ: [
    {
      ques: 'What is OSN+?',
      ans: 'OSN+ is a subscription-based streaming service where you can watch the latest and the best movies and series from HBO, Paramount+, NBC/Universal, OSN+ Originals and many more. Watch English content with Arabic subtitles, or watch Arabic content – with our affordable monthly price plan. Choose our yearly plan to save even more. Stream OSN+ on your TV, smartphones, tablets, or laptops – anytime, anywhere and without interruption.',
    },
    {
      ques: 'How is OSN+ different from OSN Streaming?',
      ans: 'OSN Streaming is now called OSN+, a name that reflects our enhanced content offerings. All OSN Streaming subscribers will continue to enjoy their favourite movies and series and more on OSN+. We are continuously working on improving your overall streaming experience. Stay tuned for exciting new updates coming your way.',
    },
    {
      ques: 'How can I use OSN+ with my OSN Streaming account?',
      ans: 'Your OSN Streaming account has automatically changed to the OSN+ account. There are no other changes to your account. You will continue enjoying five individual profiles for family & friends, personalized recommendations, exclusive access to top-notch Western, Arabic and Turkish content and much more.',
    },
    {
      ques: 'Where can I watch OSN+?',
      ans: 'Whether you have a Smart TV, Apple TV or Android TV, iOS or Android phones or tablets, PCs or Mac, or even a projector, OSN+ has you covered. We accommodate a wide range of Smart TVs, such as LG, Samsung, Sony, Hisense. Stream with Chromecast or Airplay. If you’d like to check a particular device, please send your request at OSN+ Help Desk requests and we will be happy to assist you.',
    },
    {
      ques: 'How can I watch OSN+ on my Smart TV?',
      ans: 'OSN+ might come pre-installed on your Smart TV. If you need to download it, search for OSN+ on your TV’s application store. If you still need some help, please check OSN+ FAQs for detailed information.',
    },
  ],
}
